### ISSUE TITLE
Joystick stops dragging on mobile phone (Android)

### ISSUE THREAD

**Issue by helios57** [wweitzel/ngx-joystick#10]
If I use the library or open the demo https://wweitzel.github.io/ngx-joystick/ after a sec when I use the joystick it stops dragging and can't be used.

Can be reproduced by using the development tools in Chrome (use "Toggle Device Toolbar") and select the mobile device.

**Comment by wweitzel** [comment]
Hi thanks for reporting! I have identified the issue and will be pushing out an update soon in the next day or so.

**Comment by wweitzel** [comment]
Hello @helios57. I have fixed this. Please install the newest version 1.0.6 for this fix.

Thanks for opening this issue!

**Comment by helios57** [comment]
Hi @wweitzel 
Thanks for such a fast response and the fix. Looks good on the demo page now, ill test in my application later.
Great library.
