### ISSUE TITLE
angular 14

### ISSUE THREAD

**Issue by BeatScherrer** [wweitzel/ngx-joystick#14]
When installing version `2.0.0` i get missing deps to angular `12.2.15`:

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.2.15" from ngx-joystick@2.0.0
npm ERR! node_modules/ngx-joystick
npm ERR!   ngx-joystick@"*" from the root project
```

**Comment by wweitzel** [comment]
@BeatScherrer Hm. Thanks for reporting. Just checking, you are installing this in an Angular 14 project right?

**Comment by wweitzel** [comment]
Oh crap, I see, its here https://github.com/wweitzel/ngx-joystick/blob/a7606c757c0e39a312be95b5dde601b5585f4925/projects/ngx-joystick/package.json#L24 

Ok I should be able to fix

**Comment by wweitzel** [comment]
@BeatScherrer Pushed a new version 2.0.1 that should now work. Let me know if there are still issues.

**Comment by BeatScherrer** [comment]
Seems to work all fine now and issue is resolved. Thanks for quick response.

**Comment by wweitzel** [comment]
Awesome. thanks again for reporting.
