### ISSUE TITLE
Dependency questions.

### ISSUE THREAD

**Issue by jmy520** [wweitzel/ngx-joystick#16]
My angular version is 13.3.0. I can't use 1.0.6 and latest version. So, how can I do.

**Comment by wweitzel** [comment]
Unfortunately this library does not support Angular 13. If possible, I'd suggest you update your Angular project to 14, and then install the latest version of this library

https://update.angular.io/

**Comment by jmy520** [comment]
But I'm now using Ionic framework, It just only supported Angular13.x.

**Comment by wweitzel** [comment]
I think Ionic supports angular 14. https://ionicframework.com/docs/angular/overview

> Ionic supports Angular version 6.0.0 and up

You might need to be using ionic version 6 to get angular 14 support
