### ISSUE TITLE
Upgrade to angular 11 ?

### ISSUE THREAD

**Issue by lycwed** [wweitzel/ngx-joystick#2]
Hi ! Simple question, will you upgrade your module to angular 11 ?

**Comment by wweitzel** [comment]
Hello! I have just updated the project and npm package. Version 1.0.1 of the npm package now works with Angular 11. Let me know if there are any issues.

**Comment by lycwed** [comment]
Great ! I will test it now !!! Thank you

Le dim. 6 déc. 2020 à 16:35, Wes Weitzel <notifications@github.com> a
écrit :

**Comment by lycwed** [comment]
I still have this WARN message when execute npm install :
```npm WARN ngx-joystick@1.0.1 requires a peer of @angular/common@^8.2.14 but none is installed. You must install peer dependencies yourself.```
```npm WARN ngx-joystick@1.0.1 requires a peer of @angular/core@^8.2.14 but none is installed. You must install peer dependencies yourself.```

**Comment by wweitzel** [comment]
That warning should not matter. The package will still work with Angular 11. Thanks for pointing that out though, I will remove that warning in a future release.

**Comment by lycwed** [comment]
it's related to the peerDependencies data in `/projects/ngx-joystick/package.json`.

**Comment by wweitzel** [comment]
Fixed and put a new version out. 1.0.2 should not have a warning on install.

**Comment by lycwed** [comment]
Awesome, thanks!

Le mar. 8 déc. 2020 à 04:10, Wes Weitzel <notifications@github.com> a
écrit :
