### ISSUE TITLE
restJoystick option does not work with x, y object config

### ISSUE THREAD

**Issue by JoeHogan** [wweitzel/ngx-joystick#20]
joystick option for restJoystick true/false works properly, with true being the default if not specified. This option should take an object as well; {x?: boolean, y?: boolean} but when setting it this way, it seems to function as if it hasnt been defined at all, meaning restJoystick: true

**Comment by JoeHogan** [comment]
Issue is that this repo is using an old version of nipplejs... i have a PR in to update it: https://github.com/wweitzel/ngx-joystick/pull/21

**Comment by wweitzel** [comment]
Nice! I will take a look at this later

**Comment by wweitzel** [comment]
Thanks, new version (3.0.2) with this change has been published to npm
