### ISSUE TITLE
Cannot set custom CSS

### ISSUE THREAD

**Issue by alexp25** [wweitzel/ngx-joystick#4]
I am trying to add custom CSS to the joystick:

```
.nipple .front {
    border: 2px solid black !important;
}
.nipple .back {
    border: 2px solid black !important;
}
```

I do not understand why these classes don't get applied. If I use the raw nipplejs in [codepen](https://codepen.io/YoannM/pen/gapmMG) it works.

**Comment by wweitzel** [comment]
Hello @alexp25, please try the following:
```
:host ::ng-deep .nipple .front {
  border: 5px solid black !important;
}
:host ::ng-deep .nipple .back {
  border: 5px solid black !important;
}
```

This is what worked for me

**Comment by ghost** [comment]
> This is what worked for me

It worked for me too. Thanks!
